### ISSUE TITLE
Installtion error

### ISSUE THREAD

**Issue by Agilitytime** [devon-mar/netbox-kea#111]
Hi,

Unfortunately, I can't succeed in installing the plugin,
could someone please list the steps for me?

sorry, i'm new to the Netbox topic...

i getting this error.

(venv) root@network:/opt/netbox/netbox# ./manage.py migrate
Traceback (most recent call last):
  File "/opt/netbox-4.0.9/netbox/netbox/settings.py", line 778, in <module>
    plugin = importlib.import_module(plugin_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'netbox_kea'

I install the dependencies 

[Kea Control Agent](https://kea.readthedocs.io/en/latest/arm/agent.html)
[lease_cmds](https://kea.readthedocs.io/en/latest/arm/hooks.html#lease-cmds-lease-commands-for-easier-lease-management) hook library

Thnaks,
Sebastian

**Comment by devon-mar** [comment]
Did you run `pip install -r local_requirements.txt` to install the plugin?

**Comment by Agilitytime** [comment]
Hi,

thanks for your answer.

I test this also and it still not works.
Did you have another Idea?

Thanks,
Sebastian

**Comment by devon-mar** [comment]
Can you try the `upgrade.sh` script? It looks like it will install the packages from `local_requirements.txt` into the correct virtual environment.
